"""user token version

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 23:21:57.663573
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op



revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
